//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public System.Guid Id { get; set; }
        public string Ma_Khach_Hang { get; set; }
        public string Ten_Khach_Hang { get; set; }
        public string CMT { get; set; }
        public string Anh_Dai_Dien { get; set; }
        public string Anh_CMT_Mat_Truoc { get; set; }
        public string Anh_CMT_Mat_Sau { get; set; }
        public string Ho_Ten { get; set; }
        public string Dia_Chi { get; set; }
        public string Gioi_Tinh { get; set; }
        public string SDT { get; set; }
        public string Nghe_Nghiep { get; set; }
        public string Noi_Cong_Tac { get; set; }
        public Nullable<bool> Dang_Ky_Tam_Tru { get; set; }
        public string Ho_Ten_Nguoi_Than { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<System.Guid> Id_Phong { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
    }
}
