//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        public System.Guid Id { get; set; }
        public string Ma_Phong { get; set; }
        public string Ten_Phong { get; set; }
        public Nullable<int> Tang { get; set; }
        public Nullable<int> So_Nguoi_Toi_Da { get; set; }
        public Nullable<int> Don_Gia { get; set; }
        public string Tinh_Trang { get; set; }
        public string Mo_Ta { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
    }
}
